/*
 * This source file was generated by the Gradle 'init' task
 */
package hexafoot;

import hexafoot.dados.LeitorCSVSelecao;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {

    @Test
    void deveLocalizarElencosCSV() {
        LeitorCSVSelecao leitor = new LeitorCSVSelecao();

        assertFalse(leitor.listarArquivosDeSelecoes().isEmpty());
    }

    @Test
    void deveEncontrarBrasilEntreOsElencos() {
        LeitorCSVSelecao leitor = new LeitorCSVSelecao();

        assertTrue(leitor.listarArquivosDeSelecoes().stream().anyMatch(arquivo -> arquivo.isBrasil()));
    }

}


